apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
spec:
  # Omit 'interfaces' to announce on all interfaces, or specify (e.g., [ "eth0" ])
  externalIPs: true
  loadBalancerIPs: true